site_name: LightGBM-Benchmark

# https://www.mkdocs.org/user-guide/configuration/
repo_url: https://github.com/Microsoft/lightgbm-benchmark
edit_uri: edit/main/docs

nav:
- Home: index.md
- About: lightgbm-benchmark-project.md
- Contribute:
    Developer Guide: contribute/developer-guide.md
    Reporting Guide: contribute/reporting-guide.md
- Run:
    Install: run/install.md
    Run manually: run/manual-benchmark.md
    Run in AzureML:
        Setup: run/azureml/setup.md
        Train on your data: "run/azureml/train-on-your-own-data.md"
- Results:
    Inferencing: results/inferencing.md
    Manual: results/manual.md

theme:
  name: readthedocs
  name: material

markdown_extensions:
- pymdownx.tabbed
- pymdownx.superfences
- pymdownx.snippets
- admonition
- pymdownx.highlight:
    use_pygments: true
    linenums: true
    linenums_style: pymdownx-inline
# https://github.com/mkdocs/mkdocs/issues/777
- markdown_include.include:
    base_path: .

plugins:
- search
- mkdocstrings