site_name: LightGBM-Benchmark

# https://www.mkdocs.org/user-guide/configuration/
repo_url: https://github.com/Microsoft/lightgbm-benchmark
edit_uri: edit/main/docs

nav:
- Home: index.md
- About: lightgbm-benchmark-project.md
- Contribute:
    Developer Guide: contribute/developer-guide.md
    Reporting Guide: contribute/reporting-guide.md
- Run:
    Install: run/install.md
    Run locally:
        Manual benchmark: run/local/manual-benchmark.md
    Run in AzureML:
        Azure Setup: run/azureml/azure-setup.md
        Local Setup: run/azureml/local-setup.md
        Upload data: run/azureml/upload-data.md
        Train on your data: run/azureml/train-on-your-data.md
- Tutorials:
    Develop:
        Create a script: tutorials/create-script.md
        Create an AzureML component: tutorials/create-azureml-component.md
    Pipelines:
        Training (single): tutorials/pipeline-training-single.md
        Training (benchmark): tutorials/pipeline-training-benchmark.md
        Inferencing (benchmark): tutorials/pipeline-inferencing-benchmark.md
- Results:
    Inferencing: results/inferencing.md
    Manual: results/manual.md

theme:
  name: readthedocs
  name: material

markdown_extensions:
- pymdownx.tabbed
- pymdownx.superfences
- pymdownx.snippets
- admonition
- pymdownx.highlight:
    use_pygments: true
    linenums: true
    linenums_style: pymdownx-inline
# https://github.com/mkdocs/mkdocs/issues/777
- markdown_include.include:
    base_path: .

plugins:
- search
- mkdocstrings