site_name: LightGBM-Benchmark

# https://www.mkdocs.org/user-guide/configuration/
repo_url: https://github.com/Microsoft/lightgbm-benchmark
edit_uri: edit/main/docs

nav:
- Home: index.md
- About: lightgbm-benchmark-project.md
- Contribute:
    Developer Guide: contribute/developer-guide.md
    Reporting Guide: contribute/reporting-guide.md
- Run:
    Install: run/install.md
    Run manually: run/manual-benchmark.md
    Run in AzureML:
        Azure Setup: run/azureml/azure-setup.md
        Local Setup: run/azureml/local-setup.md
        Upload data: run/azureml/upload-data.md
        Train on your data: run/azureml/train-on-your-data.md
- Results:
    Inferencing: results/inferencing.md
    Manual: results/manual.md
- Reference Docs:
    - src/common/:
        - io.py: references/common/io.md
        - lightgbm.py: references/common/lightgbm.md
        - metrics.py: references/common/metrics.md
        - sweep.py: references/common/sweep.md
        - tasks.py: references/common/tasks.md
    - src/scripts/:
        - partition_data/partition.py: references/scripts/partition_data/partition.md

theme:
  name: readthedocs
  name: material

markdown_extensions:
- pymdownx.tabbed
- pymdownx.superfences
- pymdownx.snippets
- admonition
- pymdownx.highlight:
    use_pygments: true
    linenums: true
    linenums_style: pymdownx-inline
# https://github.com/mkdocs/mkdocs/issues/777
- markdown_include.include:
    base_path: .

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
        python:
            setup_commands:
            - import sys
            - sys.path.append("src")
            rendering:
                show_source: true
                show_if_no_docstring: false
                members_order: "source"
                show_root_toc_entry: false
                show_root_heading: false
    #custom_templates: templates
    watch:
      - src/
