name: lightgbm_data2bin_env
channels:
- defaults
dependencies:
- python=3.8
- pip=20.0
- pip:
  - numpy==1.21.2
  - scikit-learn==0.24.2
  - azureml-defaults==1.35.0
  - azureml-mlflow==1.35.0
  - psutil==5.8.0
  - lightgbm==3.2.1
  - matplotlib==3.4.3
