name: treelite_conda_env
channels:
- defaults
dependencies:
- python=3.8
- pip=22.2.2
- pip:
  - numpy==1.21.2
  - scikit-learn==0.24.2
  - azureml-defaults==1.35.0
  - azureml-mlflow==1.35.0
  - psutil==5.8.0
