name: treelite_conda_env
channels:
- defaults
dependencies:
- python=3.8
- pip=20.0
- pip:
  - azureml-defaults==1.35.0
  - azureml-mlflow==1.35.0
  - treelite==2.1.0
  - treelite_runtime==2.1.0
  - pandas>=1.1,<1.2
  - numpy>=1.10,<1.20
  