name: AzureML Pipelines

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    environment: mlops

    runs-on: ubuntu-latest

    steps:
  
    - name: check out repo
      uses: actions/checkout@v2

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.MLOPS_AZURE_CREDS}}
