name: AzureML Pipelines Validation

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    environment: mlops

    runs-on: ubuntu-latest

    steps:
  
    - name: check out repo
      uses: actions/checkout@v2

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDS}}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.1 pytest~=6.2 pytest-cov~=2.11
        sudo apt-get install libopenmpi-dev
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name : Validate pipelines [data generation]
      run: >-
        python pipelines/data_generation.py
        --config-dir ./conf
        --config-name experiments/data-generation
        aml.subscription_id=${{secrets.SUBSCRIPTION}}
        aml.resource_group=${{secrets.RESOURCE_GROUP}}
        aml.workspace_name=${{secrets.WORKSPACE_NAME}}
        aml.auth="azurecli"
      working-directory: pipelines/azureml/

    - name : Validate pipelines [inferencing]
      run: >-
        python pipelines/lightgbm_inferencing.py
        --config-dir ./conf
        --config-name experiments/inferencing
        aml.subscription_id=${{secrets.SUBSCRIPTION}}
        aml.resource_group=${{secrets.RESOURCE_GROUP}}
        aml.workspace_name=${{secrets.WORKSPACE_NAME}}
        aml.auth="azurecli"
      working-directory: pipelines/azureml/

    - name : Validate pipelines [training]
      run: >-
        python pipelines/lightgbm_training.py
        --config-dir ./conf
        --config-name experiments/lightgbm_training/cpu
        aml.subscription_id=${{secrets.SUBSCRIPTION}}
        aml.resource_group=${{secrets.RESOURCE_GROUP}}
        aml.workspace_name=${{secrets.WORKSPACE_NAME}}
        aml.auth="azurecli"
      working-directory: pipelines/azureml/

    - name : Validate pipelines [training+sweep]
      run: >-
        python pipelines/lightgbm_training.py
        --config-dir ./conf
        --config-name experiments/lightgbm_training/sweep
        aml.subscription_id=${{secrets.SUBSCRIPTION}}
        aml.resource_group=${{secrets.RESOURCE_GROUP}}
        aml.workspace_name=${{secrets.WORKSPACE_NAME}}
        aml.auth="azurecli"
      working-directory: pipelines/azureml/
