name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
    - 'docker/**'
    - '.github/workflows/docker_images.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'docker/**'
    - '.github/workflows/docker_images.yml'

jobs:

  linux_container_build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - lightgbm-v3.2.1/linux_cpu_mpi_build.dockerfile
          - lightgbm-v3.2.1/linux_cpu_mpi_pip.dockerfile
          - lightgbm-v3.2.1/linux_cuda_build.dockerfile
          - lightgbm-v3.2.1/linux_gpu_build.dockerfile
          - lightgbm-v3.2.1/linux_gpu_pip.dockerfile
          - lightgbm-v3.3.0/linux_cpu_mpi_build.dockerfile
          - lightgbm-v3.3.0/linux_cpu_mpi_pip.dockerfile
          - lightgbm-custom/v321_patch_cpu_mpi_build.dockerfile

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
        
    - uses: marceloprado/has-changed-path@v1
      id: dockerfile-changed
      with:
        paths: docker/${{ matrix.dockerfile}}

    - name: Build the Docker image
      if: steps.dockerfile-changed.outputs.changed == 'true'
      run: docker build . --file ${{ matrix.dockerfile }} --tag temp:$(date +%s) --build-arg lightgbm_benchmark_branch=${{ steps.extract_branch.outputs.branch }}
      working-directory: docker/

  windows_container_build:

    runs-on: windows-latest

    strategy:
      matrix:
        dockerfile:
          - lightgbm-v3.2.1/windows_cpu_pip.dockerfile
          - lightgbm-v3.3.0/windows_cpu_pip.dockerfile

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: marceloprado/has-changed-path@v1
      id: dockerfile-changed
      with:
        paths: docker/${{ matrix.dockerfile}}

    - name: Build the Docker image
      if: steps.dockerfile-changed.outputs.changed == 'true'
      run: docker build . --file ${{ matrix.dockerfile }} --tag temp:$(date +%s)
      working-directory: docker/
