name: docs

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v1

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: pip install
      run: |
        python -m pip install markdown-include==0.6.0 mkdocstrings==0.15.0 mkdocs-material==7.1.3 livereload==2.6.3

    - name: build docs
      run: |
        mkdocs build

    - name: deploy docs
      if: github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
        git remote rm origin
        git remote add origin "${remote_repo}"
        mkdocs gh-deploy --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --force
